import { Inter } from "next/font/google";
import Topbar from "@/app/components/Topbar";
import RightBar from "@/app/components/RightBar";
import LeftBar from "@/app/components/LeftBar";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: {
    default: "Dua & Ruqyah | All Duas Collection",
    template: "%s | All Duas Collection",
  },
  description: "Generated by Sabbir",
  icons: {
    icon: ["https://duaruqyah.com/assets/dua-logo.svg"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-10">
      <body className="bg-[#ebeef2] relative">
        <div
          className={`${inter.variable} false z-0 lg:fixed lg:inset-x-0 xl:fixed xl:inset-x-0 xl:p-6 xl:pb-0 2xl:px-10 2xl:pt-6 2xl:fixed 2xl:inset-x-0 3xl:p-10 3xl:pb-0 3xl:fixed 3xl:inset-x-0`}
        >
          <div className="relative grid gap-6 sm-max:overflow-auto xs:flex xs:flex-col xs:gap-0 sm:gap-0 xl:grid-rows-[46px,1fr] 2xl:grid-rows-[46px,1fr] 3xl:grid-rows-[46px,1fr] z-0 xl:grid-cols-[105px,350px,1fr] 2xl:grid-cols-[105px,350px,1fr,270px] 3xl:grid-cols-[105px,350px,1fr,300px]">
            <div className="row-span-full hidden xl:block xl:z-[-1] 2xl:block 2xl:z-[-1] 3xl:block 3xl:z-[-16]">
              <LeftBar />
            </div>
            <div className="xl:col-start-2 xl:col-span-full 2xl:col-start-2 2xl:col-span-full 2xl:z-[-1] 3xl:col-start-2 3xl:col-span-full 3xl:z-[-16]">
              <Topbar />
            </div>
            {/* main part */}
            <div className="md:z-[-3] md-max:flex md-max:w-full lg-min:grid-cols-[350px,1fr] lg:gap-6 lg:z-[-2] xl-min:col-span-2 xl:gap-x-6 2xl:gap-x-6 2xl:z-[-1] 2xl-min:w-full 3xl:gap-x-6 3xl:z-[-16] grid xs:mx-auto sm:mx-auto md:mx-auto lg:w-[96%] lg:mx-auto mt-6 2xl:col-span-2">
              {children}
            </div>
            <div className="hidden 2xl:block 3xl:block 3xl:col-start-4 2xl:col-start-4 3xl:-z-[17] z-[-2] my-6">
              <RightBar />
            </div>
            <main className="hidden"></main>
          </div>
        </div>
      </body>
    </html>
  );
}
